### ISSUE TITLE
Does not longer work with demo 0.5.0.11991

### ISSUE THREAD

**Issue by frasosatis** [glcoder/ScienceUnlock#1]
ScienceUnlock does not work with new demo (itch.io only) 0.5.0.11991.
However, the code change is quite small. All required to do is to comment the " __instance.includeInBuild = true;" lines as this seems not longer to be part of the ItemTemplate.

**Comment by glcoder** [comment]
Hello, I have access to itch.io version, I'll check fix on the new demo and if everything goes fine I'll merge your request.

**Comment by glcoder** [comment]
I've checked version 0.5.0.11991 and mod must be rebuild using new `Main.dll` because `includeInBuild` field was moved from `ItemTemplate` to it's partent class `TemplateObject`. New build will be added to Releases section, no changes in code needed.
